---
- name: Configure mysql server
  hosts: mysql
  become: true
  vars:
    mysql_ip: "{{ mysql_ip }}"
  tasks:
    - name: Start server
      systemd:
        name: mysql.service
        state: started
      register: mysql_start

    - name: Print status
      debug:  
        var: mysql_start.stdout_lines

    - name: Comment Lines
      lineinfile:
        regexp: "^(bind-address|mysqlx-bind-address)"
        line: "# {{ item }}"
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
      with_items:
        - bind-address            = 127.0.0.1
        - mysqlx-bind-address     = 127.0.0.1

    - name: Perform configuration
      lineinfile:
        line: |
            port=3306
            bind_address="{{ mysql_ip }}"
            mysqlx-bind-address="{{ mysql_ip }}"
            # general
            max_connections=4000
            table_open_cache=8000
            table_open_cache_instances=16
            back_log=1500
            default_password_lifetime=0
            ssl=0
            performance_schema=OFF
            max_prepared_stmt_count=128000
            skip_log_bin=1
            character_set_server=latin1
            collation_server=latin1_swedish_ci
            transaction_isolation=REPEATABLE-READ
            # files
            innodb_file_per_table
            innodb_log_file_size=1024M
            innodb_log_files_in_group=8 #scale
            innodb_open_files=4000
            # buffers
            innodb_buffer_pool_size=24000M #scale
            innodb_buffer_pool_instances=16
            innodb_log_buffer_size=64M
            # tune
            innodb_doublewrite=0
            innodb_thread_concurrency=0
            innodb_flush_log_at_trx_commit=0
            innodb_max_dirty_pages_pct=90
            innodb_max_dirty_pages_pct_lwm=10
            join_buffer_size=32K
            sort_buffer_size=32K
            innodb_use_native_aio=1
            innodb_stats_persistent=1
            innodb_spin_wait_delay=6
            innodb_max_purge_lag_delay=300000
            innodb_max_purge_lag=0
            innodb_flush_method=O_DIRECT_NO_FSYNC
            innodb_checksum_algorithm=none
            innodb_io_capacity=1000
            innodb_io_capacity_max=2000
            innodb_lru_scan_depth=9000
            innodb_change_buffering=none
            innodb_read_only=0
            innodb_page_cleaners=4
            innodb_undo_log_truncate=off
            # perf special
            innodb_adaptive_flushing=1
            innodb_flush_neighbors=0
            innodb_read_io_threads=16
            innodb_write_io_threads=16
            innodb_purge_threads=4
            innodb_adaptive_hash_index=0
            # monitoring
            innodb_monitor_enable='%'
        insertafter: EOF 
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        state: present

    - name: Restart mysql
      systemd: 
        name: mysql.service
        state: restarted

    - name: Get status
      shell: sudo systemctl status mysql.service
      register: mysql_status

    - name: Print status
      debug:  
        var: mysql_status.stdout_lines

    - name: Create mysql user
      shell: |
        sudo mysql -e "CREATE USER 'mysql'@'10.63.20.89' IDENTIFIED BY 'admin'; GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'10.63.20.89' WITH GRANT OPTION; ALTER USER 'mysql'@'10.63.20.89' IDENTIFIED WITH mysql_native_password BY 'admin';"
        sudo mysql -e "CREATE USER 'mysql'@'%' IDENTIFIED BY 'admin'; GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'%' WITH GRANT OPTION; ALTER USER 'mysql'@'%' IDENTIFIED WITH mysql_native_password BY 'admin';"
        
        




        


