---
- name: Restore DB
  hosts: postgres
  become: true
  tasks:
    - name: Stop db
      command:
        cmd: su - postgres -c "pg_ctl -D $PGDATA stop"
      register: restore_stop_db_status
    - name: Display status
      debug:
        var: restore_stop_db_status
    - name: Delete, copy, move and link files
      shell: >
        rm -rf /var/lib/postgresql/14/main/*

        rm -rf /var/lib/postgresql/14/log/*

        cp -R /var/lib/postgresql/14/backups/main/* /var/lib/postgresql/14/main/

        cp /var/lib/postgresql/14/main/pg_wal /var/lib/postgresql/14/log

        ln -s /var/lib/postgresql/14/log/pg_wal /var/lib/postgresql/14/main/pg_wal
    - name: give permissions
      file:
        path: /var/lib/postgresql/14/main/
        owner: postgres
        group: postgres
    - name: Set directory permissions
      file:
        path: /var/lib/postgresql/14/main/
        mode: "0700"
        recurse: yes
        state: directory
    - name: Start DB
      become: true
      command:
        cmd: su - postgres -c "pg_ctl -D $PGDATA start"
      register: restore_start_db_status
    - name: Display status
      debug:
        var: restore_start_db_status
    - name: Reboot machine
      reboot:
        reboot_timeout: 600
